### ISSUE TITLE
Specify the source of benchmarks in README files

### ISSUE THREAD

**Issue by wukefe** [Sable/Ostrich2#29]
**Do we need to clarify the source of benchmarks?**  A benchmark may derive from other benchmarks or relate to interesting problems.

Also, we can have a brief summary of the whole benchmarks, including the supported languages and platforms.   Take a look at [benchmark games](http://benchmarksgame.alioth.debian.org/).

**Comment by elavoie** [comment]
Yes we should. How do you suggest we do  it? In the Ostrich v1, we had README files. I removed them to put the description mentioning the source in the benchmark.json file. But maybe I should put them back? What do you think?

**Comment by wukefe** [comment]
Right, I have found the description in each benchmark.json.  However, the description of benchmarks does not show the origin of benchmarks.  Sometimes, it is not nothing from nothing.  If one benchmark (maybe only C code) is influenced by other benchmarks, we should acknowledge their contribution somewhere (i.e. README files).  We can leave the work at the end after we complete the benchmarks.

**Comment by elavoie** [comment]
Ok, then let's add README files with acknowledgement from the source. I'll do it onward for the new benchmarks and add it to the olds.

**Comment by elavoie** [comment]
All the benchmarks now have README files explicitly mentioning the source of the benchmarks. I'll make sure the others do too.

**Comment by wukefe** [comment]
That's good.  Thanks.

**Comment by elavoie** [comment]
Done for all benchmarks that required it.
