### ISSUE TITLE
backprop matlab: Error when running 'wu run backprop none-matlab matlab-vm' 

### ISSUE THREAD

**Issue by elavoie** [Sable/Ostrich2#71]
-------------- backprop,matlab,none-matlab,mba-2011,matlab-vm --------------
{ type: 'experiment',
  'short-name': 'default',
  'input-size': 'medium',
  'iteration-number': 1 }
*************\* Iteration 0 ************

```
                        < M A T L A B (R) >
              Copyright 1984-2015 The MathWorks, Inc.
               R2015b (8.6.0.267246) 64-bit (maci64)
                          August 20, 2015
```

To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

```
----------------------------------------------------
Your MATLAB license will expire in 52 days.
Please contact your system administrator or
MathWorks to renew this license.
----------------------------------------------------

Academic License
```

Undefined function 'createMatrixRandJS' for input arguments of type 'double'.

**Comment by wukefe** [comment]
@elavoie,

Two problems:

1) The synthesized code under `builds/xxx/runner.m` has a problem in concatenating functions.  The code looks like:

```
disp(msg);
endfunction [hidden_weights] = bp_core(input_units,hidden_units,input_weights,in,hid,out,output_delta,target,outp    ...
```

The words 'end' and 'function' are put together.

2) Add the following library file to support the missing function **commonRandomJS**.  But the code doesn't work.  Could you please take a look at the library files in MATLAB support?  I will quickly fix the similar problems later.

```
"libraries":[
         { "suite-root": "/implementations/matlab/commonRandomJS.m" }
     ]
```

Thanks,

**Comment by wukefe** [comment]
I think I have identified where the problem comes.  I will report it later.

Brief ideas:
- Missing library mfiles
- Incorrect synthesized code

**Comment by wukefe** [comment]
It is weird that I find in a `cat` command.  In line 762 of `wu-wei-benchmarking-toolkit/lib/config.js`, I output the variable `cmd` which invokes the `cat` to put source code and libraries into a runner file.  However, it is very strange that the input files are not correctly concatenated.

Initially, I suspect that the file format may cause the problem because the file is created on Windows.  But I check every char in the source file and there is no special character that Mac OS may be confused.

```
/bin/cat  xxx/benchmarks/backprop/implementations/matlab/runner.m xxx > runner.m
```

Could you please take a look at the `runner.m` file?  Thanks.

**Comment by elavoie** [comment]
The contatenation is probably not working because there is no newline at
the end of the matlab runner file. If you add one that should work.

**Comment by elavoie** [comment]
I will add the missing end-of-lines in backprop and all the other matlab benchmarks and I will look into the missing library.

**Comment by elavoie** [comment]
I created a utility script 'cat-with-nl' that concatenate and add newlines between files to avoid the issue. I have added it to the utility folder in Ostrich2. See 174b89f9e633dbb01c85a0bd4a477cd02f506797 and c4f11ed22533fefe5a05712d7aa420d788b9eed6.

**Comment by elavoie** [comment]
I have added the missing libraries into the implementation.json file for the backprop matlab implementation. See 12e43a3ef09baeaa183c836156fee87d0b724742.

**Comment by elavoie** [comment]
The benchmark should now run, albeit rather slow because the data generation is slow with the current method. I will create another issue for that.
