### ISSUE TITLE
crc matlab: Error when running 'wu run none-matlab matlab-vm crc' 

### ISSUE THREAD

**Issue by elavoie** [Sable/Ostrich2#73]
-------------- crc,matlab,none-matlab,mba-2011,matlab-vm --------------
{ type: 'experiment',
  'short-name': 'default',
  'input-size': 'medium',
  'iteration-number': 1 }
*************\* Iteration 0 ************

```
                        < M A T L A B (R) >
              Copyright 1984-2015 The MathWorks, Inc.
               R2015b (8.6.0.267246) 64-bit (maci64)
                          August 20, 2015
```

To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

```
----------------------------------------------------
Your MATLAB license will expire in 52 days.
Please contact your system administrator or
MathWorks to renew this license.
----------------------------------------------------

Academic License
```

Error: File: Ostrich2/builds/1389ee160d324b7799b605da5e65a339d9654463/runner.m Line: 63 Column: 5
"length" previously appeared to be used as a function or command, conflicting with its use here as the name of a variable.
A possible cause of this error is that you forgot to initialize the variable, or you have initialized it implicitly using load or eval.

**Comment by wukefe** [comment]
How to configure the `implementation.json` for multiple parameters?

``` json
"medium": {
            "page-size": 65536,
            "page-nb": 128,
            "repetitions": 150 
        },  
```

**Comment by elavoie** [comment]
@wukefe See the previous commit to see how I added multiple arguments passing. I essentially added the 'path' property to the 'expand' object. The 'path' refers to a property of an object being expanded. I'll explain it to you tomorrow in the lab once I am back ;-).

**Comment by wukefe** [comment]
@elavoie Thank you.  I will check the commit to figure out how to add multiple parameters.  Then, I could solve the referred similar issues.  I'm looking forward to seeing you tomorrow.  Have a nice and safe trip!

**Comment by elavoie** [comment]
@wukefe Thanks! See you soon!
