### ISSUE TITLE
hmm matlab: Error when running 'wu run none-matlab matlab-vm hmm' 

### ISSUE THREAD

**Issue by elavoie** [Sable/Ostrich2#75]
-------------- hmm,matlab,none-matlab,mba-2011,matlab-vm --------------
{ type: 'experiment',
  'short-name': 'default',
  'input-size': 'medium',
  'iteration-number': 1 }
*************\* Iteration 0 ************

```
                        < M A T L A B (R) >
              Copyright 1984-2015 The MathWorks, Inc.
               R2015b (8.6.0.267246) 64-bit (maci64)
                          August 20, 2015
```

To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

```
----------------------------------------------------
Your MATLAB license will expire in 52 days.
Please contact your system administrator or
MathWorks to renew this license.
----------------------------------------------------

Academic License
```

Error: File: /Users/erick/Documents/Recherche/Ostrich2/builds/4693df730f7cb9c94f1508b85a93303488e4660d/runner.m Line: 176 Column: 1
"pi" previously appeared to be used as a function or command, conflicting with its use here as the name of a variable.
A possible cause of this error is that you forgot to initialize the variable, or you have initialized it implicitly using load or eval.

**Comment by wukefe** [comment]
The similar question I have asked in #73 

``` json
"medium": {
            "model": "n",
            "nb-states": 512 
        },  
```

From: `benchmarks/hmm/benchmark.json`

**Comment by wukefe** [comment]
Solve. See 91142040acaf1c352ac6b370b1f2abd6568eb7f7
