### ISSUE TITLE
nw matlab: Error when running 'wu run none-matlab matlab-vm nw' 

### ISSUE THREAD

**Issue by elavoie** [Sable/Ostrich2#77]
-------------- nw,matlab,none-matlab,mba-2011,matlab-vm --------------
{ type: 'experiment',
  'short-name': 'default',
  'input-size': 'medium',
  'iteration-number': 1 }
*************\* Iteration 0 ************

```
                        < M A T L A B (R) >
              Copyright 1984-2015 The MathWorks, Inc.
               R2015b (8.6.0.267246) 64-bit (maci64)
                          August 20, 2015
```

To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

```
----------------------------------------------------
Your MATLAB license will expire in 52 days.
Please contact your system administrator or
MathWorks to renew this license.
----------------------------------------------------

Academic License
```

Error: File: Ostrich2/builds/3405815566a945f73a1e0d2de91d33627a025112/runner.m Line: 170 Column: 6
This statement is not inside any function.
 (It follows the END that terminates the definition of the function "runner".)

**Comment by wukefe** [comment]
In `benchmarks/nw/implementations/matlab/implementation.json`, the configuration of two input data files is incorrect.  The two data files should be removed from `"runner-arguments"`.  However, I don't know where to put the two data files.  Could you please take a look, @elavoie ?  Thanks.

``` json
{ "file": "./seq1.data"},
{ "file": "./seq2.data"} 
```

**Comment by wukefe** [comment]
Fixed.  See 6ee560e54e8708b4df76a0e04c84b2871d649a5c
