### ISSUE TITLE
Installation instructions: `utilities/browser-run` does not exist

### ISSUE THREAD

**Issue by martinforsythe** [Sable/Ostrich2#90]
The Wiki indicates that installation should use `npm install` within a directory `utilities/browser-run`, but that directory (and the corresponding node configuration files) does not exist in the repository. Can you provide installation instructions?

**Comment by elavoie** [comment]
Hi @mbloodforsythe. What are you using the Ostrich benchmarks for?

This repo was meant to overhaul the entire suite and combine with all other benchmarks our lab was using. However, it started being unmanageable, newer projects did not use the Ostrich benchmarks, and therefore the full port of the old Ostrich benchmarks was never completed.

I am currently busy with other projects but I will come back to that during the summer and hopefully by September the overhaul should be completed with much nicer tools to work with. I would suggest you use the old repository https://github.com/Sable/Ostrich until then. I will update the readme to make it clearer.

**Comment by martinforsythe** [comment]
Hi @elavoie thanks for the info. I started looking at the Ostrich benchmarks because it looked like a reasonably well documented / put together benchmark suite and I wanted to compare a probabilistic programming package that I've been working on developing against an external implementation of an HMM or other graphical model inference problem.

**Comment by elavoie** [comment]
Ok. It has been a while so I might have forgotten but I think the HMM implementation in the suite was ported from OpenCL to other languages (our paper says that we used the OpenCL version without modification and added other language implementations). We worked hard to make sure the input values were the same between language implementations and make sure the output would be consistent across language implementations as much as possible to make sure we did not introduce bugs in the translation process.

I also tried to make sure the algorithm was computing the right thing (I found bugs in the original Needleman-Wunch benchmark) but did not have time to do that for all benchmarks and I did not do HMM. If you have good experience with the algorithm, it would be great if you could make sure the code is computing the right thing and report back.

**Comment by elavoie** [comment]
The README was updated to reflect the situation.
