### ISSUE TITLE
Can't find browser-run

### ISSUE THREAD

**Issue by wukefe** [Sable/Ostrich2#91]
Where is the file `browser-run` for [installation](https://github.com/Sable/Ostrich2/wiki/Installation)?

```shell
cd utilities/browser-run
npm install
```

In order to run none-js option, I have to install many modules one-by-one.  By all means, I think a list of all of these modules should be saved somewhere and can be installed with `npm install`.

**Comment by elavoie** [comment]
Ostrich2 is deprecated. With the latest version of wu-wei, simply install [ostrich-suite](https://github.com/Sable/ostrich-suite) as an artifact by doing:

> mkdir ostrich-repo
cd ostrich-repo
wu init
wu install https://github.com/Sable/ostrich-suite.git

**Comment by wukefe** [comment]
Thanks.  I will try the new repo.
